In [96]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import joblib

# Types of Categorical Variable:
     
    1. Nominal Variable: Variable has no relationship with eachother.
      Example: # male,female
               # kathmandu,bhaktapur,lalitpur
               above variable has no relationship with each other.
      To solve this problem one of the method is one_hot_encoding
    2. Ordinal Variable: Variable has relationship with eachother.
       Example: # high ,medium,low --> high > medium > low
                # phd,master,graduate --> phd > master > graduate

In [64]:
df=pd.read_csv("F:\\mysql\\py-master\\py-master\\ML\\5_one_hot_encoding\\homeprices.csv")

In [65]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [70]:
df1=pd.get_dummies(df.town)
df1

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [83]:
merged=pd.concat([df,df1],axis="columns")

In [84]:
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [92]:
df_final=merged.drop(columns=["town","robinsville"],axis="columns")

In [93]:
df_final

area   price  monroe township  west windsor
0   2600  550000                1             0
1   3000  565000                1             0
2   3200  610000                1             0
3   3600  680000                1             0
4   4000  725000                1             0
5   2600  585000                0             1
6   2800  615000                0             1
7   3300  650000                0             1
8   3600  710000                0             1
9   2600  575000                0             0
10  2900  600000                0             0
11  3100  620000                0             0
12  3600  695000                0             0

In [94]:
model=linear_model.LinearRegression()
model.fit(df_final[["area","monroe township","west windsor"]],df_final.price)

LinearRegression()

In [103]:
joblib.dump(model,"one_hot_model")

['one_hot_model']

In [104]:
model1=joblib.load("one_hot_model")

In [106]:
model.coef_

array([   126.89744141, -25686.4115244 ,  14327.56396474])

In [107]:
model.intercept_


235462.803698204

In [108]:
model1.intercept_

235462.803698204

In [109]:
model1.coef_


array([   126.89744141, -25686.4115244 ,  14327.56396474])

In [110]:
model1.predict([[2800,0,0]])

c:\users\acer\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.6396474])

In [111]:
model1.predict([[2800,1,0]])

c:\users\acer\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([565089.22812299])

In [112]:
model1.predict([[2800,0,1]])

c:\users\acer\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([605103.20361213])

In [113]:
x=df_final.drop(columns=["price"])

In [116]:
y=df_final.drop(x,axis="columns")

In [118]:
model1.score(x,y)

0.9573929037221872