In [14]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import joblib

In [3]:
df=pd.read_csv("F:\\mysql\\py-master\\py-master\\ML\\5_one_hot_encoding\\Exercise\\carprices.csv")

In [4]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [5]:
df1=pd.get_dummies(df["Car Model"])

In [6]:
df1

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [9]:
merge=pd.concat([df,df1],axis="columns")
merge

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6        0       1   
1                  BMW X5    35000          34000         3        0       1   
2                  BMW X5    57000          26100         5        0       1   
3                  BMW X5    22500          40000         2        0       1   
4                  BMW X5    46000          31500         4        0       1   
5                 Audi A5    59000          29400         5        1       0   
6                 Audi A5    52000          32000         5        1       0   
7                 Audi A5    72000          19300         6        1       0   
8                 Audi A5    91000          12000         8        1       0   
9   Mercedez Benz C class    67000          22000         6        0       0   
10  Mercedez Benz C class    83000          20000         7        0       0   
11  Mercedez Benz C class    79000          21000         7        0       0   
12  Mercedez Benz C class    59000          33000         5        0       0   

    Mercedez Benz C class  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
5                       0  
6                       0  
7                       0  
8                       0  
9                       1  
10                      1  
11                      1  
12                      1

In [11]:
df_final=merge.drop(["Car Model","Mercedez Benz C class"],axis="columns")

In [12]:
df_final

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [22]:
x=df_final.drop("Sell Price($)",axis="columns")
y=df_final.drop(x,axis="columns")
y

Sell Price($)
0           18000
1           34000
2           26100
3           40000
4           31500
5           29400
6           32000
7           19300
8           12000
9           22000
10          20000
11          21000
12          33000

In [25]:
model=linear_model.LinearRegression()
model.fit(x,y)

LinearRegression()

In [27]:
model.coef_
model.intercept_

array([58976.62596854])

In [28]:
 joblib.dump(model,"model1")

['model1']

In [29]:
 model1=joblib.load("model1")

In [48]:
model1.coef_

array([[-3.70122094e-01, -1.33245363e+03, -2.45354074e+03,
        -6.73820733e+03]])

In [49]:
model1.intercept_


array([58976.62596854])

In [32]:
model.score(x,y)

0.9417050937281082

In [33]:
model1.score(x,y)

0.9417050937281082

In [38]:
x

Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6        0       1
1     35000         3        0       1
2     57000         5        0       1
3     22500         2        0       1
4     46000         4        0       1
5     59000         5        1       0
6     52000         5        1       0
7     72000         6        1       0
8     91000         8        1       0
9     67000         6        0       0
10    83000         7        0       0
11    79000         7        0       0
12    59000         5        0       0

In [42]:
model1.predict([[73000,6,1,0]])

c:\users\acer\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[21509.45057525]])

In [44]:
MODEL=linear_model.LinearRegression()
MODEL.fit(df_final[["Mileage","Age(yrs)","Audi A5","BMW X5"]],df_final["Sell Price($)"])

LinearRegression()

In [47]:
MODEL.predict([[45000,4,0,1]])

c:\users\acer\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([30253.10988495])