In [73]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [74]:
flowers=load_iris()

In [75]:
dir(flowers)


['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [76]:
flowers.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [77]:
flowers.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [78]:
flowers.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [79]:
flowers.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [80]:
df=pd.DataFrame(flowers.data,columns=["sepal_length","sepal_width","petal_length","width"])

In [81]:
df.head()

sepal_length  sepal_width  petal_length  width
0           5.1          3.5           1.4    0.2
1           4.9          3.0           1.4    0.2
2           4.7          3.2           1.3    0.2
3           4.6          3.1           1.5    0.2
4           5.0          3.6           1.4    0.2

In [82]:
df["target"]=flowers.target

In [83]:
X=df.drop("target",axis="columns")
y=df.target

In [85]:
from sklearn.model_selection import train_test_split

In [86]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=4)

In [87]:
def score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [88]:
score(LogisticRegression(),X_train,X_test,y_train,y_test)

c:\users\acer\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9333333333333333

In [89]:
score(SVC(),X_train,X_test,y_train,y_test)

0.9333333333333333

In [90]:
score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.8666666666666667

In [154]:
score_Lr=[]
score_svm=[]
score_Rf=[]
from sklearn.model_selection import StratifiedKFold
kf=StratifiedKFold(n_splits=3)

In [155]:
for train,test in kf.split(flowers.data,flowers.target):
    X_train,X_test,y_train,y_test=flowers.data[train],flowers.data[test],flowers.target[train],flowers.target[test]
    score_Lr.append(score(LogisticRegression(),X_train,X_test,y_train,y_test))
    score_svm.append(score(SVC(),X_train,X_test,y_train,y_test))
    score_Rf.append(score(RandomForestClassifier(),X_train,X_test,y_train,y_test))
    

c:\users\acer\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [156]:
score_svm

[0.96, 0.98, 0.94]

In [157]:
score_Rf

[0.98, 0.94, 0.98]

In [158]:
score_Lr

[0.98, 0.96, 0.98]

In [162]:
from sklearn.model_selection import cross_val_score

In [163]:
cross_val_score(RandomForestClassifier(),flowers.data,flowers.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])